### ISSUE TITLE
Error while making target

### ISSUE THREAD

**Issue by ManInBlackie** [CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch#95]
I get this error while running make target:
```

Traceback (most recent call last):
  File "C:/Users/x/Desktop/EverybodyDanceNow_reproduce_pytorch-master/make_target.py", line 93, in <module>
    head_cord = cord[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/x/Desktop/EverybodyDanceNow_reproduce_pytorch-master/make_target.py", line 95, in <module>
    head_cord = pose_cords[-1] # if there is not head point in picture, use last frame
IndexError: list index out of range
```

cord is empty, what can I do?

**Comment by dklingmann** [comment]
It's possible a typo was made when creating the folders/images for the target data.
Therefore, when you open that data, it remains empty.

Can you confirm this is still an ongoing issue? If not, please close it.
