### ISSUE TITLE
TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by ManInBlackie** [CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch#96]
python: 3.8.6
windows: 10
Got this error while trying to run transfer.py, for what I read on StackOverflow it is not solvable on windows

```
Traceback (most recent call last):
  File "C:/Users/x/Desktop/EverybodyDanceNow_reproduce_pytorch-master/transfer.py", line 29, in <module>
    for data in tqdm(dataset):
  File "C:\Users\x\Desktop\EverybodyDanceNow_reproduce_pytorch-master\instapy-quickstart-master\lib\site-packages\tqdm\std.py", line 1166, in __iter__
    for obj in iterable:
  File "C:\Users\x\Desktop\EverybodyDanceNow_reproduce_pytorch-master\instapy-quickstart-master\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\x\Desktop\EverybodyDanceNow_reproduce_pytorch-master\instapy-quickstart-master\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\x\Desktop\EverybodyDanceNow_reproduce_pytorch-master\instapy-quickstart-master\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object
```

**Comment by akaihaoshuai** [comment]
https://github.com/yanx27/EverybodyDanceNow_reproduce_pytorch/issues/77#issuecomment-804027650

set nThreads=0 in test_opt.py
